### ISSUE TITLE
Prompts not being processed

### ISSUE THREAD

**Issue by dr3nan** [leetcode-mafia/cheetah#11]
Hello there,

I have everything set and the prompts are being transcripted into the app, but once I press on Analise, it does nothing.
<img width="871" alt="Screenshot 2023-04-18 at 09 20 47" src="https://user-images.githubusercontent.com/19169582/232703721-050b4caf-8bee-4393-95a7-8a70e6371c68.png">

Is there a need to have SIP off or something?

Great work btw

**Comment by leetcode-mafia** [comment]
Run the app directly from the Terminal to see error logs:

```shell
/Applications/Cheetah.app/Contents/MacOS/Cheetah
```

What do you see?

**Comment by dr3nan** [comment]
Here it is when I select device
![Screenshot 2023-04-18 at 19 44 08](https://user-images.githubusercontent.com/19169582/232860457-c37d974a-7b77-4afc-b057-66399462591c.png)

Here at launch
![Screenshot 2023-04-18 at 19 46 28](https://user-images.githubusercontent.com/19169582/232863949-d509b324-6dfb-4071-8338-4cd33f7ee4a2.png)

**Comment by leetcode-mafia** [comment]
What about when you click Answer?

**Comment by useless-plant** [comment]
I have this issue too, when I click answer nothing new appears in terminal or in the app. My logs look identical to @dr3nan. 

```
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1024
whisper_model_load: n_audio_head  = 16
whisper_model_load: n_audio_layer = 24
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1024
whisper_model_load: n_text_head   = 16
whisper_model_load: n_text_layer  = 24
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 4
whisper_model_load: mem required  = 1725.00 MB (+   43.00 MB per decoder)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     = 1462.35 MB
whisper_model_load: model size    = 1462.12 MB
whisper_init_state: kv self size  =   42.00 MB
whisper_init_state: kv cross size =  140.62 MB
```

**Comment by dr3nan** [comment]
> What about when you click Answer?

Well, nothing ever really happens besides transcribing. If I wait till the transcription is finished and press the answer button, nothing happens. A short spinner loader happens, about 1000ms +-.

Can't even highlight text from transcription.

**Comment by leetcode-mafia** [comment]
Released a new version that should now show an error message when this happens: https://github.com/leetcode-mafia/cheetah/releases/tag/v1.1

**Comment by dr3nan** [comment]
> Released a new version that should now show an error message when this happens: https://github.com/leetcode-mafia/cheetah/releases/tag/v1.1

here is the error code
<img width="412" alt="Screenshot 2023-04-19 at 21 45 51" src="https://user-images.githubusercontent.com/19169582/233183892-e2d6ebc6-bdd5-481e-ad71-58f2c02c86a4.png">

**Comment by liembow** [comment]
> 

The same issue is happening with me

**Comment by leetcode-mafia** [comment]
Do you have access to GPT-4?

**Comment by liembow** [comment]
> 

Yes , I do

**Comment by liembow** [comment]
I downloaded the new version and now I'm getting this new error message:
![image](https://user-images.githubusercontent.com/131304440/233209063-85c73723-8878-497b-a26d-ae1497f94d53.png)

**Comment by maurolonmartin** [comment]
i couldn't understand how to run the project, any help?

**Comment by liembow** [comment]
It's working now, god bless you man @leetcode-mafia , I had to pay for the Open AI API, I thought it worked with the Chat GPT Plus subscription but it's different, for me it doesn't work with gpt-4, it says the model is unavailable
