### ISSUE TITLE
When I was testing, I reported an error. The data couldn t be read because it is missing.

### ISSUE THREAD

**Issue by Bob4F** [leetcode-mafia/cheetah#17]
<img width="840" alt="WeChat596590818efd7ebb5649540a2ff741ab" src="https://user-images.githubusercontent.com/46439335/234479355-9d179e98-8629-4b94-b8a2-02a856681e9c.png">

**Comment by Bob4F** [comment]
@leetcode-mafia Please help me

**Comment by Bob4F** [comment]
<img width="279" alt="WeChatdfa9395e647ca7916166b587a4269c35" src="https://user-images.githubusercontent.com/46439335/234509978-2d97081e-7a74-4e4f-bcd5-1a88e8b0cf95.png">
<img width="659" alt="WeChat9970d0f24c31c584338251cef4a4e02c" src="https://user-images.githubusercontent.com/46439335/234510137-6bdae3a9-04d2-4592-8fd6-85dd74ed3f0a.png">
I've configured the multi-output device BlackHole in audio

**Comment by leetcode-mafia** [comment]
See https://github.com/leetcode-mafia/cheetah/issues/11#issuecomment-1515447730

**Comment by Bob4F** [comment]
use GPT-4？

**Comment by leetcode-mafia** [comment]
> use GPT-4？

I don't understand the question, sorry.

**Comment by Bob4F** [comment]
The audio is all set up, and the multilingual model is configured, but the audio has no way to recognize Chinese

**Comment by Bob4F** [comment]
> > use GPT-4？
> 
> I don't understand the question, sorry.
The audio is all set up, and the multilingual model is configured, but the audio has no way to recognize Chinese

**Comment by Bob4F** [comment]
> See [#11 (comment)](https://github.com/leetcode-mafia/cheetah/issues/11#issuecomment-1515447730)

Do you mean you need to use the account of the ChatGPT Plus?

**Comment by leetcode-mafia** [comment]
No, you need [API access](https://openai.com/waitlist/gpt-4-api) and a [payment method](https://platform.openai.com/account/billing/overview) on file.

**Comment by leetcode-mafia** [comment]
The error message should be clearer in [v1.3](https://github.com/leetcode-mafia/cheetah/releases/tag/v1.3), please verify.

**Comment by Bob4F** [comment]
> The error message should be clearer in [v1.3](https://github.com/leetcode-mafia/cheetah/releases/tag/v1.3), please verify.

It did not solve my problem. When I tested with my friend, Blank audio was displayed all the time, and our conversation was in Chinese

**Comment by Bob4F** [comment]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/46439335/234858893-63ef8134-f608-4353-bb2c-47271472ecd4.png">

**Comment by Bob4F** [comment]
<img width="773" alt="WeChat5b445a3f2059f28f2e81e34007779453" src="https://user-images.githubusercontent.com/46439335/234859068-5f7fb679-9f4a-4b41-8cff-eea05bb5d0fd.png">

**Comment by Bob4F** [comment]
Why is mine always 'blank audio'

**Comment by Bob4F** [comment]
I guess our conversation wasn't captured. We were using the Zoom App

**Comment by Bob4F** [comment]
Now you can see the text communicated by Zoom App, but when I click Answer, it only turns around, and then there is no response

**Comment by leetcode-mafia** [comment]
Only English is currently supported, see #13.
