### ISSUE TITLE
"Cheetah" app unexpectedly shutting down

### ISSUE THREAD

**Issue by EvilevNikita** [leetcode-mafia/cheetah#18]

**Comment by EvilevNikita** [comment]
<img width="632" alt="Снимок экрана 2023-04-26 в 12 25 55" src="https://user-images.githubusercontent.com/116057796/234492022-05ae61fd-aa6b-436f-9c89-7db7eed0ff9f.png">

**Comment by Bob4F** [comment]
It may be because you installed the SDL2 of 86_64, you need to install the S D L of the ARM64 version

**Comment by EvilevNikita** [comment]
> 
Can you tell me where I can find instructions on how to install ARM 64? I can not(

**Comment by Bob4F** [comment]
install arm64 homebrew，After the installation is successful, uninstall the existing sdl2，invoke'arch -arm64 brew install sdl2'

**Comment by leetcode-mafia** [comment]
This should be fixed in [v1.3](https://github.com/leetcode-mafia/cheetah/releases/tag/v1.3), please verify.

**Comment by EvilevNikita** [comment]
Yes 1.3 is working. Thanks! And Bob4F also thanks!
