### ISSUE TITLE
Macbook pro m1 is hot

### ISSUE THREAD

**Issue by EvilevNikita** [leetcode-mafia/cheetah#19]
I don’t know why, but my macbook processor is very hot from the cheetah
<img width="542" alt="Снимок экрана 2023-04-27 в 14 26 26" src="https://user-images.githubusercontent.com/116057796/234804874-74fd447f-3c97-4e2e-9d98-2fe1124ec5ed.png">

**Comment by leetcode-mafia** [comment]
This is normal. Whisper is highly CPU intensive.
