### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by clopezAlternova** [leetcode-mafia/cheetah#20]
hello good,

Earlier I assigned a chatgpt 3.5 key but now I want to assign the version 4 key.
I have modified the code so that it receives the new key but that value is still stored somewhere, I tried to download the repository again and execute it but it still does not work.

in the cheetahApp add the following line
@Published var authToken: String? = "tokens"
but I don't know where the previous token is still stored

i have this message
![Screenshot 2023-05-03 at 6 18 28 PM](https://user-images.githubusercontent.com/131046563/236071712-5a71cbc2-003d-4a14-8c84-e1135a467c4d.png)

You exceeded your current quota, please check your plan and billing details.

**Comment by leetcode-mafia** [comment]
You can change the API key via the app menu, here:

<img width="257" src="https://user-images.githubusercontent.com/106342593/236701012-81f52c21-eb71-4dd9-8176-2e5669694601.png">
