### ISSUE TITLE
Showing All Errors Only Build input file cannot be found: 'mypath/whisper.cpp/whisper.cpp'. 

### ISSUE THREAD

**Issue by buildingios** [leetcode-mafia/cheetah#21]
I cloned git repository by terminal: 

 `git clone https://github.com/leetcode-mafia/cheetah.git`
 
 open `Cheetah.xcodeproj` and saw next error:

` Showing All Errors Only Build input file cannot be found: '/Users/k.kh/Projects/whisper.cpp/whisper.cpp'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?`

how I can fix that ?

**Comment by clopezAlternova** [comment]
you need to put your proyect in the same level that whisper, for example. both in desk or documents
