### ISSUE TITLE
Stuck at the download ggml section

### ISSUE THREAD

**Issue by soapzi17** [leetcode-mafia/cheetah#25]
<img width="300" alt="image" src="https://github.com/leetcode-mafia/cheetah/assets/13375036/3d6418d9-95b2-4ded-b7fa-02f7aad4675d">

I have already checkout the whisper at parent directory and have already downloaded the ggml model at the whisper directory. But I still have this download modal showing up. Clean build and rerun still show the same modal, Need some help, thanks.

**Comment by leetcode-mafia** [comment]
What kind of network are you connected to? The model is 1.4 GB, so it can take a while to download if bandwidth is constrained. Also, the app won't try to download it over a metered network e.g. personal hotspot (you can edit [CheetahApp.swift](https://github.com/leetcode-mafia/cheetah/blob/b7e301c0ae16df5c597b564b2126e10e532871b2/Cheetah/CheetahApp.swift#L55) to remove that restriction).
