### ISSUE TITLE
You exceeded your current quota, please check you plan and billing details.

### ISSUE THREAD

**Issue by soapzi17** [leetcode-mafia/cheetah#26]
<img width="259" alt="image" src="https://github.com/leetcode-mafia/cheetah/assets/13375036/6a128ebb-66eb-4216-a3e3-c5377eeffb8f">

This error modal pops up when I try the first time and clicking the Answer button, I have GPT plus, is there any way to switch Cheetah from GPT4 to GPT3.5 or is there any way to update keys? Thanks.

**Comment by leetcode-mafia** [comment]
You can change the API key or switch to GPT-3.5 in the app menu:

<img width="257" src="https://user-images.githubusercontent.com/106342593/236701012-81f52c21-eb71-4dd9-8176-2e5669694601.png">

However, it still won't work unless you have a credit card on file for the API.

**Comment by MyEnthusiastic** [comment]
where is the APP menu, how to open that
