### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by dr3nan** [leetcode-mafia/cheetah#7]
Hello, there is this error report while trying to open the app in Ventura on an M1 device.

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Cheetah [2677]
Path:                  /private/var/folders/*/Cheetah.app/Contents/MacOS/Cheetah
Identifier:            org.phrack.Cheetah
Version:               1.0 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-17 08:30:34.8688 +0200
OS Version:            macOS 13.2.1 (22D68)
Report Version:        12
Anonymous UUID:        49C72EEB-26E3-780A-D6D7-BDE5137C1587

Time Awake Since Boot: 640 seconds

System Integrity Protection: enabled

Notes:
dyld_process_snapshot_create_for_process failed with 5

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libSDL2-2.0.0.dylib
Referenced from: <9B8FE8CD-BF45-3125-B461-787CE8A00B5D> /private/var/folders/*/Cheetah.app/Contents/Frameworks/LibWhisper.framework/Versions/A/LibWhisper
Reason: tried: '/opt/homebrew/*/libSDL2-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libSDL2-2.0.0.dylib' (no such file), '/opt/homebrew/*/libSDL2-2.0.0.dylib' (no such file), '/usr/local/lib/libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Error Formulating Crash Report:
dyld_process_snapshot_create_for_process failed with 5

Thread 0 Crashed:
0   dyld                          	       0x19bbdb190 __abort_with_payload + 8
1   dyld                          	       0x19bbe5a00 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x19bbe5a34 abort_with_payload + 16
3   dyld                          	       0x19bb740a4 dyld4::halt(char const*) + 328
4   dyld                          	       0x19bb71098 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4204
5   dyld                          	       0x19bb6fdc4 start + 2404

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f089b00   x3: 0x00000000000000ff
    x4: 0x000000016f089700   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x0000000000000003  x15: 0xffffffffffffffff
   x16: 0x0000000000000209  x17: 0x000000019bb6d344  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f089700  x21: 0x00000000000000ff  x22: 0x000000016f089b00  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001f792b600  x26: 0x000000016f08b320  x27: 0x000000016f08b188
   x28: 0x0000000000000000   fp: 0x000000016f0896d0   lr: 0x000000019bbe5a00
    sp: 0x000000016f089690   pc: 0x000000019bbdb190 cpsr: 0x00001000
   far: 0x0000000100ee4000  esr: 0x56000080  Address size fault

Binary Images:
       0x19bb6a000 -        0x19bbf4ba3 dyld (*) <191e84f1-4b95-39c8-b253-1c1ef56c0fa8> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=9104K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9104K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            1139K      219 
__AUTH_CONST                      17.9M      406 
__CTF                               756        1 
__DATA                            7932K      395 
__DATA_CONST                      18.2M      410 
__DATA_DIRTY                      1258K      132 
__FONT_DATA                        2352        1 
__LINKEDIT                       768.9M        4 
__OBJC_CONST                      2113K      176 
__OBJC_RO                         65.5M        1 
__OBJC_RW                         1988K        1 
__TEXT                           406.5M      429 
dyld private memory                512K        2 
===========                     =======  ======= 
TOTAL                              1.3G     2180 

-----------
Full Report
-----------

{"app_name":"Cheetah","timestamp":"2023-04-17 08:30:35.00 +0200","app_version":"1.0","slice_uuid":"10508b98-f87d-3108-ae0b-8b6d2152a64c","build_version":"1","platform":1,"bundleID":"org.phrack.Cheetah","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2.1 (22D68)","roots_installed":0,"name":"Cheetah","incident_id":"4E5BCBB4-72B3-41B3-859A-960365331031"}
{
  "uptime" : 640,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 876,
  "osVersion" : {
    "train" : "macOS 13.2.1",
    "build" : "22D68",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-17 08:30:34.8688 +0200",
  "incident" : "4E5BCBB4-72B3-41B3-859A-960365331031",
  "pid" : 2677,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-17 08:30:34.8447 +0200",
  "procStartAbsTime" : 15419458671,
  "procExitAbsTime" : 15419988263,
  "procName" : "Cheetah",
  "procPath" : "\/private\/var\/folders\/*\/Cheetah.app\/Contents\/MacOS\/Cheetah",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1","CFBundleIdentifier":"org.phrack.Cheetah"},
  "storeInfo" : {"deviceIdentifierForVendor":"4325B34F-73A9-5FA4-B9AF-D697F3C4BD79","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.phrack.Cheetah",
  "crashReporterKey" : "49C72EEB-26E3-780A-D6D7-BDE5137C1587",
  "throttleTimeout" : 2147483647,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/opt\/homebrew\/*\/libSDL2-2.0.0.dylib","Referenced from: <9B8FE8CD-BF45-3125-B461-787CE8A00B5D> \/private\/var\/folders\/*\/Cheetah.app\/Contents\/Frameworks\/LibWhisper.framework\/Versions\/A\/LibWhisper","Reason: tried: '\/opt\/homebrew\/*\/libSDL2-2.0.0.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/opt\/homebrew\/*\/libSDL2-2.0.0.dylib' (no such file), '\/opt\/homebrew\/*\/libSDL2-2.0.0.dylib' (no such file), '\/usr\/local\/lib\/libSDL2-2.0.0.dylib' (no such file), '\/usr\/lib\/libSDL2-2.0.0.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":20090,"threadState":{"x":[{"value":6},{"value":1},{"value":6157802240},{"value":255},{"value":6157801216},{"value":0},{"value":0},{"value":0},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":50},{"value":3},{"value":18446744073709551615},{"value":521},{"value":6907417412,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6157801216},{"value":255},{"value":6157802240},{"value":1},{"value":6},{"value":8448554496,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":6157808416},{"value":6157808008},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6907910656},"cpsr":{"value":4096},"fp":{"value":6157801168},"sp":{"value":6157801104},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6907867536,"matchesCrashFrame":1},"far":{"value":4310581248}},"frames":[{"imageOffset":463248,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":506368,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":506420,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":41124,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":0},{"imageOffset":28824,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4204,"imageIndex":0},{"imageOffset":24004,"symbol":"start","symbolLocation":2404,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6907404288,
    "size" : 568228,
    "uuid" : "191e84f1-4b95-39c8-b253-1c1ef56c0fa8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=9104K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9104K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1139K      219 \n__AUTH_CONST                      17.9M      406 \n__CTF                               756        1 \n__DATA                            7932K      395 \n__DATA_CONST                      18.2M      410 \n__DATA_DIRTY                      1258K      132 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       768.9M        4 \n__OBJC_CONST                      2113K      176 \n__OBJC_RO                         65.5M        1 \n__OBJC_RW                         1988K        1 \n__TEXT                           406.5M      429 \ndyld private memory                512K        2 \n===========                     =======  ======= \nTOTAL                              1.3G     2180 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e3d2fc54bc3389840661",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "642ccaf45954e610b552219b"
      },
      "deploymentId" : 240000389
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000012
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_create_for_process failed with 5"
]
}

Model: MacBookAir10,1, BootROM 8419.80.7, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: 38GN950, 3840 x 1600 (Ultra-wide 4K), Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Nov 30 2022 03:35:43 version 18.20.379.9.7.8.145 FWID 01-9578a936
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB2.1 Hub
USB Device: USB2.0 HUB
USB Device: Razer Ornata Chroma
USB Device: USB C Video Adaptor
USB Device: HyperX Pulsefire Dart
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.
`

**Comment by dr3nan** [comment]
Installing SDL2 with brew sorted the issue

**Comment by leetcode-mafia** [comment]
Thanks for the report, I updated the readme.
