### ISSUE TITLE
Change GPT secret key

### ISSUE THREAD

**Issue by aperezgarcia93** [leetcode-mafia/cheetah#8]
How can I change the key after I have submitted one?

**Comment by dr3nan** [comment]
You need to go to /library/preferences and edit org.phrack.Cheetah.plist, then save and re-launch. Dev hasn't created settings.

**Comment by leetcode-mafia** [comment]
Run this:

```shell
defaults delete org.phrack.Cheetah authToken
```

**Comment by leetcode-mafia** [comment]
Added a menu item to change the key: https://github.com/leetcode-mafia/cheetah/releases/tag/v1.1
