### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by wangdepin** [leetcode-mafia/cheetah#9]
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/38637596/232537462-1033a9cf-dda1-483e-b44f-073a9fafcf5a.png">
Thank you so much for your tool. Could you tell me how to change the font size?

**Comment by dr3nan** [comment]
@wangdepin did you manage to make it work? It can listen to prompts, but it does nothing with it. Pressing the Analise button does nothing.

**Comment by leetcode-mafia** [comment]
Have a look [here](https://github.com/leetcode-mafia/cheetah/blob/main/Cheetah/Views/CoachView.swift#L64).
